---
site_name: Secjector
site_description: >-
  Tiny, local-only secrets accessor for MikroTik RouterOS scripts.
repo_url: https://github.com/bpopovych/secjector
repo_name: bpopovych/secjector
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.code.copy
nav:
  - Home: index.md
  - Usage: usage.md
  - Security: security.md
  - FAQ: faq.md
  - Roadmap: roadmap.md
  - CI: ci.md
markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - md_in_html
extra_css:
  - stylesheets/maintainers.css
extra:
  version:
    provider: mike
